---
- hosts: all
  tasks:
    - name: install httpd package
      yum:
        name: apache2
        update_cache: yes
        state: present
    - name: start httpd service
      service:
        name: apache2
        state: started
