---
- hosts: all
  gather_facts: no
  tasks:
    - name: installing httpd pkg
      become: yes
      yum:
        name: httpd
        state: present
        update_cache: yes 
    - name: start httpd service
      become: yes
      service:
        name: httpd
        state: stopped
      register: httpd_status
    - name: start httpd service
      become: yes
      service:
        name: httpd
        state: started
      when: httpd_status is failed

