- name: Test play
  hosts: all

  tasks:

    - name: Register a variable
      ansible.builtin.shell: cat /etc/motd
      register: motd_contents

    - name: Use the variable in conditional statement
      ansible.builtin.shell: echo "motd contains the word hi"
      when: motd_contents.stdout.find('hi') != -1
