---
- name: Install web application packages
  hosts: all
  tasks:
  - name: Includes the tasks file and defines the variables
    include_vars: variables.yml
  - name: Debugs the variables imported
    vars:
      packages:
        web_package: vim
        db_package: mongodb
    debug:
      msg: >
        "{{ packages.web_package }} and {{ packages.db_package }} have been imported"
